[package]
name = "resdet-sys"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license = "MIT AND LGPL-2.1"
description = "Low-level FFI bindings to libresdet"

links = "resdet"
include = [
    "src/**/*",
    "resdet/**/*",
    "../LICENSE-MIT",
    "../LICENSE-LGPL",
    "./wrapper_test.c"
]

[dependencies]

[build-dependencies]
cc.workspace = true
