[package]
name = "resdet-py"
version = "0.1.0"
edition = "2024"
license = "MIT AND LGPL-2.1"
description = "Safe Python bindings to libresdet for detecting upscaled images"
repository = "https://github.com/noaione/resdet-bindings"
keywords = ["image", "upscaling", "detection", "resdet"]
categories = ["multimedia::images"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
resdet = { path = "../resdet" }
rayon = "1.11.0"

[lib]
name = "_resdet"
crate-type = ["cdylib"]
