[package]
name = "resdet-py"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license = "MIT AND LGPL-2.1"
description = "Safe Python bindings to libresdet for detecting upscaled images"

[dependencies]
pyo3.workspace = true
rayon.workspace = true
resdet = { path = "../resdet" }

[lib]
name = "_resdet"
crate-type = ["cdylib"]
