[project]
name = "resdet"
description = "Detect source resolution of upscaled images"
authors = [
    {name = "noaione", email = "noaione@n4o.xyz"},
]
maintainers = [
    {name = "noaione", email = "noaione@n4o.xyz"},
]
license = { text = "MIT" }
keywords = ["image", "detection", "resdet", "resolution", "upscaling"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPL)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Typing :: Typed",
]
requires-python = ">=3.10,<3.14"
dynamic = ["version", "readme"]

[project.urls]
Homepage = "https://github.com/noaione/resdet-bindings"
Repository = "https://github.com/noaione/resdet-bindings.git"
Issues = "https://github.com/noaione/resdet-bindings/issues"
Changelog = "https://github.com/noaione/resdet-bindings/blob/master/CHANGELOG.md"

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.maturin]
python-source = "src-maturin"
module-name = "resdet._resdet"
bindings = "pyo3"
include = ["LICENSE-MIT", "LICENSE-LGPL"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["Q", "RUF100", "C90", "I"]
extend-ignore = [
    "E721",  # using type() instead of isinstance() - we use this in tests
]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
mccabe = { max-complexity = 13 }
isort = { known-first-party = ["resdet", "tests"] }