[project]
name = "resdet"
description = "Detect source resolution of upscaled images"
authors = [
    {name = "noaione", email = "noaione@n4o.xyz"},
]
maintainers = [
    {name = "noaione", email = "noaione@n4o.xyz"},
]
license = { text = "MIT" }
keywords = ["image", "detection", "resdet", "resolution", "upscaling"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPL)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Rust",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Typing :: Typed",
]
requires-python = ">=3.10,<3.15"
dynamic = ["version", "readme"]

[project.urls]
Homepage = "https://github.com/noaione/resdet-bindings"
Repository = "https://github.com/noaione/resdet-bindings.git"
Issues = "https://github.com/noaione/resdet-bindings/issues"
Changelog = "https://github.com/noaione/resdet-bindings/blob/master/CHANGELOG.md"

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[tool.maturin]
python-source = "src-maturin"
module-name = "resdet._resdet"
bindings = "pyo3"
include = ["LICENSE-MIT", "LICENSE-LGPL"]

[tool.ruff]
line-length = 120
extend-exclude = [
    "env",
    "venv",
    ".pytest_cache",
    ".venv",
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".vscode",
    ".ruff_cache",
    "**/Lib/**",
    "dist",
    "build",
    "_templates",
    "tools",
]
target-version = "py310"

[tool.ruff.format]
preview = true
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "S",
    "B",
    "T",
    "Q",
    "D",
    "RUF",
    "COM",
    "PTH",
    "ASYNC"
]
ignore = [
    "E203",
    "F405",
    "F403",
    "F722",
    "N806",
    "COM812",
    "D400",  # first line should be period, most of my docstring will be LICENSE header so no thanks
    "D202",
    "D401",
    "CPY",
]
preview = true
extend-ignore = ["D", "S603", "S404", "T201"] # D -> Docstring missing for public function or method

[tool.ruff.lint.pydocstyle]
convention = "numpy"
ignore-decorators = ["typing.overload"]

[tool.ruff.lint.isort]
combine-as-imports = false
split-on-trailing-comma = true
required-imports = ["from __future__ import annotations"]
known-first-party = ["tests", "resdet"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "I002", "D205"]
"tests/*" = ["S101", "I002"]