[package]
name = "resdet"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
description = "Safe Rust bindings to libresdet for detecting upscaled images"

[dependencies]
thiserror.workspace = true
resdet-sys = { path = "../resdet-sys" }
